spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: ${PG_URL:jdbc:postgresql://localhost:5432/your-db}
    username: ${PG_ROOT:root}
    password: ${PG_PASS:pass}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:5}
      jdbc-url: ${PG_URL:jdbc:postgresql://localhost:5432/your-db}
      schema: public
springdoc:
  swagger-ui:
    path: api
jwt:
  token:
    secret: secret
