spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: ${SCHEMA_NAME:task_management_system}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: user
    password: pass
    driverClassName: org.postgresql.Driver
  profiles:
    active: local
springdoc:
  swagger-ui:
    path: api
jwt:
  token:
    secret: secret
